### ISSUE TITLE
Cannot fetch binary data?

### ISSUE THREAD

**Issue by RickvdP** [php-riak/riak-client#16]
Hi @FabioBatSilva,

I am not sure what is happening, but the library seems to struggle (read: crash) when trying to retrieve binary data.

```
[23-Apr-2016 14:12:59 Europe/Berlin] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'None has no value.' in project/vendor/phpoption/phpoption/src/PhpOption/None.php:38
Stack trace:
#0 project/vendor/php-riak/riak-client/src/Riak/Client/Core/Transport/Proto/Kv/ProtoGet.php(70): PhpOption\None->get()
#1 project/vendor/php-riak/riak-client/src/Riak/Client/Core/RiakProtoTransport.php(87): Riak\Client\Core\Transport\Proto\Kv\ProtoGet->send(Object(Riak\Client\Core\Message\Kv\GetRequest))
#2 project/vendor/php-riak/riak-client/src/Riak/Client/Core/Operation/Kv/FetchOperation.php(52): Riak\Client\Core\RiakProtoTransport->send(Object(Riak\Client\Core\Message\Kv\GetRequest))
#3 project/vendor/php-riak/riak-client/src/Riak/Client/Core/RiakNode.php(41): Riak\Client\Core\Operation\Kv\FetchOperation->execute(Object(Riak\Client\Core\RiakProtoTransport))
#4 project/vendor/php-riak/riak in project/vendor/phpoption/phpoption/src/PhpOption/None.php on line 38
```

The Fetch code comes straight from the docs:

```
$namespace = new RiakNamespace('xxx', 'xxxx');
$location  = new RiakLocation($namespace, 'xxxx');

$fetch  = FetchValue::builder($location)
    ->withNotFoundOk(true)
    ->withR(1)
    ->build();

$result = $riak->execute($fetch);
$object = $result->getValue();

var_dump($object);
```

Everything goes well when I'm trying to fetch an object containing text, but crashes with the exception above when I'm trying to fetch an object containing binary data. The binary data and the log files both get stored through the library as well, and that seems to work without any issues.

When I'm trying to access the binary object through HTTP through a browser I can properly download the object.

Do you have any idea?

Thanks for your help.

**Comment by FabioBatSilva** [comment]
Hi @RickvdP,

I suspect it is something related to how [centraldesktop/protobuf-php](https://packagist.org/packages/centraldesktop/protobuf-php) handle empty values.

Can you attach the payload/response you have ?

``` bash
curl -v http://riak.dev:8098/buckets/${bucket}/keys/${key}

# * Connected to riak.dev
# ....
# * Connection #0 to host riak.dev left intact
```

I also have a [branch](https://github.com/php-riak/riak-client/tree/protobuf) moving from [centraldesktop/protobuf-php](https://packagist.org/packages/centraldesktop/protobuf-php) to [protobuf-php/protobuf](https://packagist.org/packages/protobuf-php/protobuf)
it is possible that it fix this problem.

**Comment by RickvdP** [comment]
Hi @FabioBatSilva,

I can share the binary blob with you directly, if you let me know how I can get it to you.

Thanks for your fast response!

**Comment by FabioBatSilva** [comment]
Thanks @RickvdP ,

email me at : `fabio.bat.silva@gmail.com`

Can you please run your tests against  `php-riak/riak-client: "dev-protobuf"` and let me know what results do you get ?

**Comment by RickvdP** [comment]
Hi @FabioBatSilva,

`dev-protobuf` unfortunately also fails, but on another error.

```
[23-Apr-2016 18:44:28 Europe/Berlin] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to read stream with 62596 bytes' in project/vendor/protobuf-php/protobuf/src/Stream.php:190
Stack trace:
#0 project/vendor/protobuf-php/protobuf/src/Binary/StreamReader.php(292): Protobuf\Stream->readStream(62596)
#1 project/vendor/php-riak/riak-client-pb/src/RpbContent.php(781): Protobuf\Binary\StreamReader->readByteStream(Object(Protobuf\Stream))
#2 project/vendor/php-riak/riak-client-pb/src/RpbGetResp.php(326): Riak\Client\ProtoBuf\RpbContent->readFrom(Object(Protobuf\ReadContext))
#3 project/vendor/protobuf-php/protobuf/src/AbstractMessage.php(29): Riak\Client\ProtoBuf\RpbGetResp->readFrom(Object(Protobuf\ReadContext))
#4 project/vendor/php-riak/riak-client/src/Riak/Client/Core/Transport/Proto/ProtoClient.php(112): Protobuf\AbstractMessage->__construct(Resource id #83)
#5 /Use in project/vendor/protobuf-php/protobuf/src/Stream.php on line 190
```

Also for this one it works fine with other objects.

I also realized that it is not necessarily failing for _all_ binary objects, just some of them (which happen to be much larger, but not sure if that is the reason).

The blob is on the way to your gmail.

**Comment by FabioBatSilva** [comment]
Thanks @RickvdP,

I'll dig into it.

**Comment by FabioBatSilva** [comment]
@RickvdP,

I wrote I simple [functional test](https://gist.github.com/FabioBatSilva/2e9b1d66f3e6d7016c2579fa12d3ac5e)
And could not reproduce using the binary you sent me or with a couple different binary i have.

By looking at the exception you have from `dev-protobuf` it seems that the binary blob returned from riak-kv is corrupted. It is supposed to have 62596 bytes but the actual blob is smaller than that.

What version of riak are you running and how is your binary data encoded ?

**Comment by RickvdP** [comment]
Hi @FabioBatSilva,

Interesting... I am running on Riak 2.1.4, latest version.

I just checked as well that based on the md5checksum values, I am getting exactly the same binary blob back from Riak (through http) as I am putting into it (through the library). 

I am a bit surprised that you are not able to reproduce the issue, which makes me suspicious of my own local dev machine and it's setup, although I have no idea what could trigger these issues as any memory or throughput settings should really not be an issue as this is not even a 64k blob...
